version: "3.9"
services:
  web-octane:
    # image: urnau/php82-app-2023:octane
    container_name: web-octane
    build:
      context: .
      dockerfile: ./docker/Dockerfile.octane
      args:
        PHP_VERSION: '8.2.4-bullseye'
    ports:
      - "80:80" #http
      - "443:443" #https

  db:
    image: mysql:latest
    ports:
      - "3306:${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_USERNAME}
      